### ISSUE TITLE
Create Killer Sudoku Grid component

### ISSUE THREAD

**Issue by Jacky-Ickx** [Jacky-Ickx/Killer-Sudoku-Helper#14]
- [x] Create Cell-Component
- [x] Cell can contain one or no value (multiple values not yet needed)
- [x] Grid-Component displays 9x9 grid (of Cell-Components)
- [x] Grid-Component can contain cages
- [x] Grid-Component correctly displays cages
- [x] Cell-Components in Grid-Component are clickable

**Comment by Y05h129** [comment]
- [x] visual difference: value and pencilmark
- [x] grid overflowwork in progress

**Comment by Jacky-Ickx** [comment]
see 3dcf940be699c34a1615c1204f606e5782f2efcc
