### ISSUE TITLE
Icon overlaps in header on small windows

### ISSUE THREAD

**Issue by Jacky-Ickx** [Jacky-Ickx/Killer-Sudoku-Helper#22]
keep icon in header:
- [x] header size should not be stretched by icon size
- [x] reduce icon size to match header

**Comment by Y05h129** [comment]
header.component.html
from: `<img max-width="40px" height="100%" alt="Killer Sudoku Helper Logo" src="favicon.ico"/>`
to:` <img alt="Killer Sudoku Helper Logo" src="favicon.ico"/>`

header.component.scss
add inside header {}:
```
img {
    height: 80%;
    width: auto;
    max-width: 4em;
  }
```
